DB_NAME: 'dead'
DB_PASSWORD: 'realboy'
AMAZON_API_KEY: AKIAJNWLHML3RJUZQ3TQ
AMAZON_SECRET_KEY: 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
BUCKET_NAME: val-mxo
GMAIL_ADDRESS: samuelmonye00@gmail.com
GMAIL_PASSWORD: redemptoristVoc22!